# Generated by Django 5.1.7 on 2025-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('last_seen_location', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='missing_persons/')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
