# Generated by Django 5.1.7 on 2025-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
