# Generated by Django 5.1.7 on 2025-03-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_missingperson_latitude_missingperson_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
