# Generated by Django 5.1.7 on 2025-03-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_missingperson_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
