# Generated by Django 5.1.7 on 2025-03-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_missingperson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='user',
        ),
    ]
