# Generated by Django 5.1.7 on 2025-03-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_missingperson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='parent_phone',
            field=models.CharField(max_length=15),
        ),
    ]
