# Generated by Django 5.1.7 on 2025-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_missingperson_parent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
