# Generated by Django 5.1.7 on 2025-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_missingperson_parent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='parent_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
