# Generated by Django 5.1.7 on 2025-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_missingperson_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='additional_audio',
            field=models.FileField(blank=True, null=True, upload_to='additional_audio/'),
        ),
    ]
