# Generated by Django 5.1.7 on 2025-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_missingperson_additional_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
